version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_tech
    environment:
      - CONFIG_PATH=/root/config/local.yaml
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avito_tech
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
