env: "local" # local, dev, prod
storage_path: "user=user password=password  host=db port=5432 dbname=avito_tech sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
