env: "local" # local, dev, prod
storage_path: "host=localhost port=5432 dbname=postgres sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypassword"